version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: passly-db
    restart: always
    environment:
      MYSQL_DATABASE: passly
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: passly_user
      MYSQL_PASSWORD: passly_password
    ports:
      - "3307:3306" # Usamos 3307 para no chocar si ya hay uno local en el 3306
    volumes:
      - ./database/passly.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  api:
    build: ./backend
    container_name: passly-api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=passly
      - JWT_SECRET=super_secret_key_passly_2026
      - JWT_EXPIRES_IN=24h
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: passly-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  mysql_data:
